name: Crystal CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v3
    - name: Install OS dependencies
      run: apt update && apt install wget
    - name: Install ImageMagick 7
      run: |
        t=$(mktemp) && \
        wget 'https://dist.1-2.dev/imei.sh' -qO "$t" && \
        bash "$t" --ci && \
        rm "$t"
    - name: Install Crystal dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
